[package]
name = "stm32-metapac-gen"
version = "0.1.0"
edition = "2018"


[dependencies]
regex = "1.5.4"
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "d5c0f6174ec7f03b5004042b788fb9fddcc7c34f" }
serde = { version = "1.0.130", features = [ "derive" ] }
serde_yaml = "0.8.21"
proc-macro2 = "1.0.29"
